voud
delete
stop
delete
void

































  gem 'httparty'
end

platforms :jruby do
  group :development do
    gem 'jruby-openssl'
  end
end

platforms :ruby do
  group :development do
    gem 'yard', '~> 0.9', '>= 0.9.11'
    gem 'redcarpet', '~> 3.2'
    gem 'github-markup', '~> 1.3'
    gem 'pry-doc', '~> 0.8'
    gem 'pry-byebug', '~> 3.2'
  end
end

gem "google-apis-core", path: "../google-apis-core"
